### ISSUE TITLE
MF3010 support

### ISSUE THREAD

**Issue by erintera** [mounaiban/captdriver#13]
Is it possible to add MF3010 support?

**lsusb** :
```
Bus 003 Device 004: ID 04a9:2759 Canon, Inc. MF3010
```
**grep 'CAPT:' /var/log/cups/error_log** :
```
D [03/Apr/2022:09:05:50 +0000] [Job 1] CAPT: rastertocapt started
D [03/Apr/2022:09:05:50 +0000] [Job 1] CAPT: printer ID string MFG:Canon;MDL:MF3010;CMD:LIPSLX,CPCA;CLS:PRINTER;DES:Canon MF3010;PESP:V1;
D [03/Apr/2022:09:05:50 +0000] [Job 1] CAPT: detected printer \'MF3010\'
E [03/Apr/2022:09:05:50 +0000] [Job 1] CAPT: unknown printer \'MFG:Canon;MDL:MF3010;CMD:LIPSLX,CPCA;CLS:PRINTER;DES:Canon MF3010;PESP:V1;\'
D [03/Apr/2022:09:05:50 +0000] [Job 1] Set job-printer-state-message to "CAPT: unknown printer \'MFG:Canon;MDL:MF3010;CMD:LIPSLX,CPCA;CLS:PRINTER;DES:Canon MF3010;PESP:V1;\'", current level=ERROR
```

**Comment by ra1nst0rm3d** [comment]
This printer uses UFR2 protocol, not CAPT. So, this is wrong driver)

**Comment by erintera** [comment]
> This printer uses UFR2 protocol, not CAPT. So, this is wrong driver)

Is there an opensource driver for UFR2 or an attempt of reverse engineering?)

**Comment by mounaiban** [comment]
For those who found this and have a UFR II printer, maybe try this [UFR II driver](https://github.com/vicamo/cndrvcups-lb)? Note that this looks like a mirror for a partially-free Canon driver that may be downloaded from any Canon official website with a little more difficulty.

Just be warned: there's a lot of blobs, and the driver hasn't been updated since 2013 as I am writing this.
