### ISSUE TITLE
Support for LBP6030B [UFRII LT]

### ISSUE THREAD

**Issue by KaurtX86** [mounaiban/captdriver#30]
Does LBP6030B has difference between LBP6000B?
Can driver for LBP6000B work with LBP6030B?
I'm not sure about that...

**Comment by mounaiban** [comment]
The LBP6030 printers do not use CAPT, but the UFR II LT protocol, according to the [specs](https://www.canon-europe.com/support/consumer_products/products/printers/laser/i-sensys_lbp6030b.html?type=specifications) on the Canon Europe website. UFR II support is beyond the scope of this project.

This issue will be closed, but I will be willing to answer any further questions to the best of my knowledge.

The LBP6030 is a particularly tricky situation, as it only hooks up via USB, so there is no working around having to reverse-engineer UFR II. Unfortunately, I do not know any public open-source project working on UFR II support.

In the meantime, there is the [cndrvcups](https://github.com/vicamo/cndrvcups-lb) repository which might contain pre-compiled binaries for UFR printers. Please be advised that the repository has not been updated since September 2013.
